Lab Assignment - 01 UCS-547-Accelerated-Data-Science


*Aditi Sikarwar 102315241*

Ans 01:

In [2]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
reverse= []
for i in range (len (arr)-1,-1,-1):
  reverse.append(arr[i])
  print(reverse)

[np.int64(5)]
[np.int64(5), np.int64(4)]
[np.int64(5), np.int64(4), np.int64(6)]
[np.int64(5), np.int64(4), np.int64(6), np.int64(3)]
[np.int64(5), np.int64(4), np.int64(6), np.int64(3), np.int64(2)]
[np.int64(5), np.int64(4), np.int64(6), np.int64(3), np.int64(2), np.int64(1)]


Other method: reverse=arr[::-1]

Ans 02.

In [5]:
import numpy as np
array1= np.array([[1,2],[3,4]])
array2=np.array([[1,2],[3,4]])
compare= array1==array2
print(compare)

[[ True  True]
 [ True  True]]


Since all elements show true, means they are all equal

Ans 3.


In [16]:
import numpy as np
x= np.array([1,2,3,4,5,1,2,1,1,1])
frequency = {}
for value in x:
  if value in frequency:
    frequency[value]+=1
  else:
      frequency[value]=1
print (frequency)
most_freq_value = max(frequency, key=frequency.get)
print (most_freq_value)
indices= []
for i in range (len(x)):
  if x[i]==most_freq_value:
     indices.append(i)
print("Most frequent value:", most_freq_value)
print("Indices:", indices)


{np.int64(1): 5, np.int64(2): 2, np.int64(3): 1, np.int64(4): 1, np.int64(5): 1}
1
Most frequent value: 1
Indices: [0, 5, 7, 8, 9]


part b solved using other **method**

In [18]:
import numpy as np
y=np.array([1,1,1,2,3,4,2,4,3,3])
values, counts = np.unique (y, return_counts=True)
most_frequent_value= values[np.argmax(counts)]
indices = np.where(y == most_freq_value)
print("Most frequent value:", most_freq_value)
print("Indices:", indices[0])



Most frequent value: 1
Indices: [0 1 2]


argmax: index of largest value


*   return_counts=True : how many times each value appears
*   np.unique: gives all different values in the array




Ans 04.

In [19]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Given matrix:")
print(gfg)
total_sum = np.sum(gfg)
print("\nSum of all elements:")
print(total_sum)
row_sum = np.sum(gfg, axis=1)
print("\nrow wise sum:")
print(row_sum)
column_sum = np.sum(gfg, axis=0)
print("\ncolumn wise sum:")
print(column_sum)

Given matrix:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

Sum of all elements:
45

row wise sum:
[[14]
 [16]
 [15]]

column wise sum:
[[20  9 16]]
